### ISSUE TITLE
NFR

### ISSUE THREAD

**Issue by ruudboon** [cvgellhorn/webpack-boilerplate#12]
Thnx for this boilerplate! 
Any plans for adding typescript support, font awesome and webpack-dashboard (when v4 support is ready)?

**Comment by cvgellhorn** [comment]
Hey @ruudboon 

I use typescript in my day-to-day work, so I put a maybe on that. Font Awesome and webpack-dashboard rather not, because I intend to keep the boilerplate as plain as possible.

Cheers
Chris

**Comment by ruudboon** [comment]
@cvgellhorn Cool, thnx. Makes sense to keep is clean.
