### ISSUE TITLE
.includes not polyfilled?

### ISSUE THREAD

**Issue by afilp** [cvgellhorn/webpack-boilerplate#151]
I get the following:

`Uncaught TypeError: ["ane","test"].includes is not a function`

In this code:
```
return["ane","test"].includes(window.params.lid)
```

Isn't the ".includes" polyfilled?

**Comment by cvgellhorn** [comment]
Hey @afilp, it's a plain boilerplate, all polyfills have to be added on a user basis. I intend to keep it as plain as possible.

Cheers Chris
