### ISSUE TITLE
Found 1 high severity vulnerability (High │ Arbitrary File Overwrite   )

### ISSUE THREAD

**Issue by martin-minghetti** [cvgellhorn/webpack-boilerplate#157]
Hello, I've been using this boilerplate a few times without any issues but today I've got these vulnerability issue and I couldn't manage to fix it... 

`High │ Arbitrary File Overwrite`
`Package │ tar`
`Patched in │ >=4.4.2 `
`Dependency of │ node-sass [dev]`
`Path │ node-sass > node-gyp > tar`
`More info │ https://npmjs.com/advisories/803`

Any help would be most welcome!

**Comment by cvgellhorn** [comment]
Hey @martin-minghetti,

I updated a bunch of packages, the issue seems to be gone. I hope this helps.

Cheers Chris
