### ISSUE TITLE
Css bundle outside of js

### ISSUE THREAD

**Issue by erichstark** [cvgellhorn/webpack-boilerplate#19]
Hello, is it possible extract css from js bundle?

[this](https://paste.ubuntu.com/p/V7gQvcgrMp/) is my config.

**Comment by nightgrey** [comment]
Okay, one more update:

extract-text-webpack-plugin is broken as of webpack@4.0.0. See this [issue](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701).

In the issue, [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) is mentioned as a workaround/temporary solution.

**Comment by cvgellhorn** [comment]
@nightgrey nice addition, thanks!
