### ISSUE TITLE
Images not copied to dist folder after built

### ISSUE THREAD

**Issue by pdnellius** [cvgellhorn/webpack-boilerplate#2]
When I go to run `npm run build`, only the .jpg files get copied to the `dist` folder, the rest of the images in `./assets/images` do not get built and copied to `./dist/assets/images`. Any insight as to why?

**Comment by cvgellhorn** [comment]
Where do you import/use the images?

**Comment by pdnellius** [comment]
In the index.ejs

**Comment by cvgellhorn** [comment]
Sorry for my late reply. I think the html-webpack-plugin has no file loader support by default.

You could use the [copy-webpack-plugin](https://github.com/kevlened/copy-webpack-plugin) to copy your assets into your dist directory. Or take a look at the html-webpack-plugin [third party addons](https://github.com/jantimon/html-webpack-plugin#third-party-addons).

Hope this helps!
