### ISSUE TITLE
Use EJS includes

### ISSUE THREAD

**Issue by isaacalves** [cvgellhorn/webpack-boilerplate#40]
Thanks for this boilerplate!

How to use EJS includes with it though?

I've tried to include an EJS template, like this:

`<%- include('header'); -%>`,

But then I get this error:

> Html Webpack Plugin:
>   ReferenceError: include is not defined
> 

I tried using [ejs-loader](https://github.com/okonet/ejs-loader) - it stops giving this error but then nothing gets compiled.

Thanks

**Comment by cvgellhorn** [comment]
Hi @isaacalves,

the ejs-loader uses lodash, which does not support `include`, this might help you further: https://github.com/okonet/ejs-loader#including-nested-templates

Cheers
Chris
