### ISSUE TITLE
Use webpack-merge rather Object.assign

### ISSUE THREAD

**Issue by QuentinRoy** [cvgellhorn/webpack-boilerplate#5]
Webpack recommands the use of [`webpack-merge`](https://github.com/survivejs/webpack-merge) for merging different configuration files (c.f. [here](https://webpack.js.org/guides/production/)).
It is probably a good idea to use it insteal of `Object.assign`.

**Comment by cvgellhorn** [comment]
Thanks for the tip, i will look into it.

**Comment by cvgellhorn** [comment]
Works well, I added it to the boilerplate.
