### ISSUE TITLE
curl script in readme and webpack-boilerplate-master

### ISSUE THREAD

**Issue by funwithtriangles** [cvgellhorn/webpack-boilerplate#8]
The script in the readme for installing the project results in the creation of a `webpack-boilerplate-master` directory. Inside the directory is `.babelrc`, `.editorconfig` and `.gitignore`. Whenever I use this boilerplate I find myself moving these files to the root and deleting the `webpack-boilerplate-master` directory.

Is there any reason for having this directory? The script in the readme is very useful but I'd much rather it started my project without that directory and the files in the correct place. :)

The script in question:

```
$ curl -L -o master.zip https://github.com/cvgellhorn/webpack-boilerplate/archive/master.zip && unzip master.zip && rm master.zip && mv ./webpack-boilerplate-master/* ./
```

**Comment by cvgellhorn** [comment]
That wasn't intended, I fixed it. ;)
